[evm]
ws_rpc_url = "ws://localhost:8545"

[broker]
type = "alpaca-broker-api"
api_key = "test_key"
api_secret = "test_secret"
account_id = "dddddddd-eeee-aaaa-dddd-beeeeeeeeeef"
mode = "sandbox"

[hyperdx]
api_key = "test-hyperdx-key"

[rebalancing]
ethereum_rpc_url = "https://mainnet.infura.io"
fireblocks_api_user_id = "example-api-user-id"
fireblocks_secret_path = "/path/to/fireblocks_secret.pem"
