database_url = ":memory:"
log_level = "debug"
server_port = 8080

order_polling_interval = 15
order_polling_max_jitter = 5

[evm]
# Base WebSocket JSON RPC URL
ws_rpc_url = "ws://localhost:8545"
# Raindex Orderbook V5 contract
orderbook = "0x1111111111111111111111111111111111111111"
# Backfill from
deployment_block = 1

[broker]
type = "alpaca-broker-api"
api_key = "test_key"
api_secret = "test_secret"
account_id = "904837e3-3b76-47ec-b432-046db621571b"

[rebalancing]
redemption_wallet = "0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
ethereum_rpc_url = "https://mainnet.infura.io"
evm_private_key = "0x0000000000000000000000000000000000000000000000000000000000000001"
usdc_vault_id = "0xfedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210"
alpaca_account_id = "904837e3-3b76-47ec-b432-046db621571b"

[rebalancing.equity_threshold]
target = "0.5"
deviation = "0.2"

[rebalancing.usdc_threshold]
target = "0.5"
deviation = "0.3"
