[evm]
ws_rpc_url = "ws://localhost:9999"

[broker]
type = "dry-run"

[hyperdx]
api_key = "e2e-test-key"

[rebalancing]
base_rpc_url = "https://localhost:9998"
ethereum_rpc_url = "https://localhost:9997"
fireblocks_api_user_id = "e2e-test-user"
fireblocks_secret_path = "/dev/null"
