[package]
name = "st0x-evm"
version = "0.1.0"
edition = "2024"

[features]
default = []
local-signer = []
fireblocks = [
  "dep:fireblocks-sdk",
  "dep:chrono",
  "dep:uuid",
  "dep:serde",
  "dep:url",
]

[dependencies]
alloy.workspace = true
async-trait.workspace = true
chrono = { workspace = true, optional = true }
fireblocks-sdk = { version = "2025.10.17", optional = true }
rain-error-decoding = { git = "https://github.com/rainlanguage/rain.error" }
serde = { workspace = true, features = ["derive"], optional = true }
thiserror.workspace = true
tracing.workspace = true
url = { workspace = true, optional = true }
uuid = { workspace = true, optional = true, features = ["v4"] }

[dev-dependencies]
httpmock.workspace = true
rand.workspace = true
rsa.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
