name: CI
on: [push]

concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

# Setting any permission drops all others to "none" by default,
# so we explicitly list every permission we need.
permissions:
  # Required by magic-nix-cache-action to authenticate
  # with the GitHub Actions cache API.
  id-token: write

  # check out the repository
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Solidity artifacts
        run: nix run .#prepSolArtifacts

      - name: Build and test
        run: nix build --impure .#st0x-liquidity

      - name: Clippy
        run: nix build --impure .#st0x-clippy

      - name: Check bun.nix is up to date
        run: |
          nix run .#genBunNix
          nix fmt -- dashboard/bun.nix
          git diff --exit-code dashboard/bun.nix

      - name: Dashboard
        run: nix build --impure .#st0x-dashboard

      - name: Flake checks
        run: nix flake check --impure
